# Generated by Django 5.2.8 on 2025-11-17 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('in_cart', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_family.family')),
            ],
            options={
                'verbose_name': 'shopping list item',
                'verbose_name_plural': 'shopping list items',
                'db_table': 'shopping_shoppinglistitem',
                'ordering': ['in_cart', '-created_at', 'name'],
                'indexes': [models.Index(fields=['family', 'in_cart'], name='shopping_sh_family__633cb0_idx')],
            },
        ),
    ]
