# Generated by Django 5.2.8 on 2025-12-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_shopping', '0001_initial'),
    ]

    operations = [
        # Add index on updated_at for general queries
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['updated_at'], name='shopping_item_updated_at_idx'),
        ),
        # Composite indexes for efficient Max() queries in polling
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['family', 'updated_at'], name='shopping_item_family_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['family', 'created_at'], name='shopping_item_family_created_idx'),
        ),
    ]
