# Generated by Django 5.2.8 on 2025-11-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='quantity',
        ),
    ]
