# Generated by Django 5.2.8 on 2025-11-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, unique=True),
        ),
    ]
