# Generated by Django 5.2.8 on 2025-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.IntegerField(default=497052, primary_key=True, serialize=False),
        ),
    ]
