# Generated by Django 5.2.8 on 2025-11-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_family', '0002_family_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, unique=True),
        ),
    ]
