# Generated by Django 5.2.8 on 2025-11-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_family', '0004_alter_family_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Lapsevanem'), ('child', 'Laps')], db_index=True, default='parent', max_length=12),
        ),
    ]
