# Generated by Django 5.2.8 on 2025-11-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_family', '0005_user_birthdate_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
