# Generated by Django 5.2.8 on 2025-11-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_family', '0006_alter_family_id_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.IntegerField(default=797926, primary_key=True, serialize=False),
        ),
    ]
