# Generated by Django 5.2.8 on 2025-12-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_family', '0007_make_email_optional_for_children'),
    ]

    operations = [
        # Add index on updated_at for efficient Max() queries in polling
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['updated_at'], name='family_family_updated_at_idx'),
        ),
    ]
