# Generated by Django 5.2.8 on 2025-11-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_family', '0008_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.IntegerField(default=963862, primary_key=True, serialize=False),
        ),
    ]
