# Generated by Django 5.2.8 on 2025-12-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rewards', '0001_initial'),
    ]

    operations = [
        # Add index on updated_at for general queries
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['updated_at'], name='rewards_reward_updated_at_idx'),
        ),
        # Composite indexes for efficient Max() queries in polling
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['family', 'updated_at'], name='rewards_reward_family_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['family', 'created_at'], name='rewards_reward_family_created_idx'),
        ),
    ]
