# Generated by Django 5.2.8 on 2025-12-01 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_tasks', '0002_task_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_occurrence', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='a_tasks.task')),
            ],
            options={
                'verbose_name': 'task recurrence',
                'verbose_name_plural': 'task recurrences',
                'db_table': 'tasks_taskrecurrence',
                'ordering': ['next_occurrence'],
                'indexes': [models.Index(fields=['task', 'next_occurrence'], name='tasks_taskr_task_id_589e74_idx'), models.Index(fields=['next_occurrence'], name='tasks_taskr_next_oc_f5cf1e_idx')],
            },
        ),
    ]
