# Generated by Django 5.2.8 on 2025-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_tasks', '0003_taskrecurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecurrence',
            name='day_of_month',
            field=models.IntegerField(blank=True, help_text='1-31 (for monthly recurrence)', null=True),
        ),
        migrations.AddField(
            model_name='taskrecurrence',
            name='day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday (for weekly recurrence)', null=True),
        ),
    ]
