# Generated by Django 5.2.8 on 2025-12-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_tasks', '0004_add_recurring_day_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecurrence',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('business_daily', 'Business Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20),
        ),
    ]
