# Generated by Django 5.2.8 on 2025-11-17 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('PRO', 'Pro')], db_index=True, default='FREE', max_length=10)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid')], db_index=True, default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscription_subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='subscriptio_owner_i_b0be37_idx'), models.Index(fields=['owner', 'tier'], name='subscriptio_owner_i_fc536a_idx'), models.Index(fields=['status', 'tier'], name='subscriptio_status_9ad170_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('tasks_created', models.PositiveIntegerField(default=0)),
                ('rewards_created', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage', to='a_family.family')),
            ],
            options={
                'verbose_name': 'subscription usage',
                'verbose_name_plural': 'subscription usages',
                'db_table': 'subscription_subscriptionusage',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['family', 'month'], name='subscriptio_family__96b583_idx')],
                'unique_together': {('family', 'month')},
            },
        ),
    ]
