# Generated by Django 5.2.8 on 2025-11-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_subscription', '0002_change_usage_to_period_based'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscriptionusage',
            name='subscriptio_family__96b583_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionusage',
            new_name='subscriptio_family__9d0616_idx',
            old_name='subscriptio_family__period_idx',
        ),
    ]
