# Generated by Django 5.2.8 on 2025-11-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_subscription', '0003_remove_subscriptionusage_subscriptio_family__96b583_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Tasuta'), ('STARTER', 'Alustaja'), ('PRO', 'Pro')], db_index=True, default='FREE', max_length=10),
        ),
    ]
