# Generated by Django 5.2.8 on 2025-12-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_subscription', '0004_update_tier_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionusage',
            name='recurring_tasks_created',
            field=models.PositiveIntegerField(default=0, help_text='Korduvate ülesannete arv (testimiseks muudetav)'),
        ),
    ]
