"""
Django settings for _core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Determine if we're in production based on environment variable
# Set DEBUG=False in Railway environment variables for production
# Defaults to True for local development
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Custom User Model
AUTH_USER_MODEL = 'a_family.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-ly*fpjg)@3k3&7-7mbnxx$qfsm*3lk0o+u)ge6^zd-tp+*yqd0')

# ALLOWED_HOSTS - in production/staging, set this via environment variable
# For Railway: Set ALLOWED_HOSTS=yourdomain.com,your-app.railway.app
# Note: Django doesn't support wildcards in ALLOWED_HOSTS, so you must specify exact domains
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    allowed_hosts = os.getenv('ALLOWED_HOSTS', '')
    if allowed_hosts:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts.split(',') if host.strip()]
    else:
        # If no ALLOWED_HOSTS is set in production, allow all (not recommended but prevents 400 errors)
        # This should be overridden with proper domain names
        import logging
        logger = logging.getLogger(__name__)
        logger.warning('ALLOWED_HOSTS not set in production! Allowing all hosts. This is insecure - set ALLOWED_HOSTS environment variable.')
        ALLOWED_HOSTS = ['*']

# Security Settings for Production
if not DEBUG:
    # HTTPS Settings
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS Settings
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Session Security
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    
    # CSRF Security
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_TRUSTED_ORIGINS = [
        origin.strip() 
        for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') 
        if origin.strip()
    ]
    
    # Content Security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'a_landing',
    'a_dashboard',
    'a_family',
    'a_subscription',
    'a_shopping',
    'a_rewards',
    'a_tasks',
    'a_account',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static file serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'a_family.middleware.EmailVerificationMiddleware',  # Check email verification
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                '_core.context_processors.debug_context',
                '_core.context_processors.subscription_context',
            ],
        },
    },
]

WSGI_APPLICATION = '_core.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

LOGIN_REDIRECT_URL = 'a_family:onboarding'
LOGIN_URL = 'account_login'
LOGOUT_REDIRECT_URL = 'a_landing:landing_index'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = 'a_family:onboarding'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = 'account_login'
ACCOUNT_SIGNUP_REDIRECT_URL = 'a_family:onboarding'
ACCOUNT_LOGOUT_REDIRECT_URL = 'a_landing:landing_index'

# Email verification - skip for children without email (handled in adapter)
# Set to 'optional' since children may not have email, but we'll require it for parents in the form
ACCOUNT_EMAIL_VERIFICATION = 'optional'
# Login methods - support both username and email login
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
# Signup fields - username required, email optional (we handle requirement in forms based on role)
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email', 'password1*', 'password2*']
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',
}
ACCOUNT_FORMS = {
    'signup': 'a_family.forms.FamilySignupForm',
}
ACCOUNT_ADAPTER = 'a_family.adapter.AsyncAccountAdapter'
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Perekas] '

# Email Configuration
# In production/staging: Set SMTP environment variables
# In local development: Uses console backend (emails print to terminal)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@perekas.ee')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

if os.getenv('EMAIL_HOST'):
    # SMTP configuration for production/staging
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
else:
    # Console backend for local development
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Railway provides DATABASE_URL automatically when PostgreSQL service is added
# For local development, falls back to SQLite

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Use PostgreSQL from Railway or other providers
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'a_family.validators.SimplePasswordValidator',
        'OPTIONS': {
            'min_length': 8,
            'max_length': None,
            'require_number': True,
            'require_uppercase': True,
        },
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'et'

TIME_ZONE = 'Europe/Tallinn'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for static file serving
# Use CompressedManifestStaticFilesStorage for production (adds cache busting)
# Falls back to CompressedStaticFilesStorage if manifest files are missing
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# WhiteNoise settings
WHITENOISE_USE_FINDERS = True  # Allow WhiteNoise to find static files during development
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh in development

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Stripe Configuration
# Use environment variables if set, otherwise use test keys for development
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', None)

# Stripe URL settings - use production URL if set, otherwise use request.build_absolute_uri()
# Set STRIPE_BASE_URL in production (e.g., https://perekas.ee)
# If not set, URLs will be built from request (useful for local development)
STRIPE_BASE_URL = os.getenv('STRIPE_BASE_URL', None)


# Stripe Price IDs
STARTER_MONTHLY_PRICE_ID = os.getenv('STARTER_MONTHLY_PRICE_ID', 'price_1SUdLt8TJMYKOD9HkQsG0t55')
STARTER_YEARLY_PRICE_ID = os.getenv('STARTER_YEARLY_PRICE_ID', 'price_1SUdLt8TJMYKOD9HFKxIhmjq')
PRO_MONTHLY_PRICE_ID = os.getenv('PRO_MONTHLY_PRICE_ID', 'price_1SUdMm8TJMYKOD9HJwhR8zvK')
PRO_YEARLY_PRICE_ID = os.getenv('PRO_YEARLY_PRICE_ID', 'price_1SUdMm8TJMYKOD9HgHoCVqds')

# Stripe Customer Portal
STRIPE_CUSTOMER_PORTAL_ID = os.getenv('STRIPE_CUSTOMER_PORTAL_ID', 'bpc_1SVHy37Bxzw7NSMsZQonrHVo')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'a_subscription': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'a_dashboard': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'a_tasks': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'a_rewards': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)
