# Generated by Django 5.2.8 on 2025-12-29 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the submitter', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Name of the submitter (optional)', max_length=255)),
                ('why_created_account', models.TextField(help_text='Why did you create an account?')),
                ('added_family_members', models.BooleanField(default=False, help_text='Did you add any family members?')),
                ('created_tasks', models.BooleanField(default=False, help_text='Did you create any tasks?')),
                ('created_rewards', models.BooleanField(default=False, help_text='Did you create any rewards?')),
                ('created_shopping_lists', models.BooleanField(default=False, help_text='Did you create any shopping lists?')),
                ('what_prevented_usage', models.TextField(blank=True, help_text='What prevented you from using the app?')),
                ('feedback', models.TextField(blank=True, help_text='Any additional feedback or suggestions?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the review (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review form submission',
                'verbose_name_plural': 'review form submissions',
                'db_table': 'landing_review_form_submission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
